# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AddLayers
                                 A QGIS plugin
 This plugin will add layers with only one button
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-08
        copyright            : (C) 2019 by TheSigProject
        email                : rdrcorvera@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AddLayers class from file AddLayers.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .add_layers import AddLayers
    return AddLayers(iface)
